### ISSUE TITLE
延期任务

### ISSUE THREAD

**Issue by lulanlan03** [neuronetio/vue-gantt-elastic#14]
@neuronetio 
如果任务超过了结束日期还没完成，也就是延期任务，想让他显示为红色，怎么添加

**Comment by neuronetio** [comment]
read [the documentation](https://gantt-schedule-timeline-calendar.neuronet.io/documentation/configuration)
if you cannot find a solution open an issue on the [original gantt repository](https://github.com/neuronetio/gantt-schedule-timeline-calendar) in english
