### ISSUE TITLE
您好，请问控制台报这些错是什么原因导致的呢？

### ISSUE THREAD

**Issue by zhangliangliangya** [neuronetio/vue-gantt-elastic#2]
Error: <rect> attribute width: Expected length, "NaN"
Error: <line> attribute x1: Expected length, "NaN"
Error: <line> attribute x2: Expected length, "NaN"
Error: <svg> attribute width: Expected length, "NaN"
Error: <svg> attribute width: Expected length, "NaNpx"

**Comment by neuronetio** [comment]
Which browser do you use?
Is the problem still present? in 1.0.0

**Comment by neuronetio** [comment]
read latest documentation, or pull latest version
